// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiOnlineBookStoreAdmin.Models;

namespace apiOnlineBookStoreAdmin.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20190412042234_updatedpart")]
    partial class updatedpart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminPassword");

                    b.Property<string>("AdminUserName");

                    b.HasKey("AdminId");

                    b.HasIndex("AdminUserName")
                        .IsUnique()
                        .HasFilter("[AdminUserName] IS NOT NULL");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorDescription");

                    b.Property<string>("AuthorImage");

                    b.Property<string>("AuthorName")
                        .HasColumnName("AuthorName")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<int>("BookCategoryId");

                    b.Property<string>("BookDescription");

                    b.Property<string>("BookImage");

                    b.Property<string>("BookName")
                        .HasColumnName("BookName")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<float>("BookPrice");

                    b.Property<string>("BookType");

                    b.Property<int>("PublicationId");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookCategoryId");

                    b.HasIndex("PublicationId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.BookCategory", b =>
                {
                    b.Property<int>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookCategoryDescription");

                    b.Property<string>("BookCategoryImage");

                    b.Property<string>("BookCategoryName")
                        .HasColumnName("BookCategoryName")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("BookCategoryId");

                    b.HasIndex("BookCategoryName")
                        .IsUnique()
                        .HasFilter("[BookCategoryName] IS NOT NULL");

                    b.ToTable("BookCategories");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<bool>("BillingAddress");

                    b.Property<long>("Contact");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("NewPassword");

                    b.Property<string>("OldPassword");

                    b.Property<string>("ShippingAddress");

                    b.Property<bool>("ShippingAddressBoolean");

                    b.Property<string>("UserName");

                    b.Property<long>("ZipCode");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<float>("OrderAmount");

                    b.Property<DateTime>("OrderDate");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.OrderBook", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<int>("BookId");

                    b.Property<int>("Quantity");

                    b.HasKey("OrderId", "BookId");

                    b.HasAlternateKey("BookId", "OrderId");

                    b.ToTable("OrderBooks");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Publication", b =>
                {
                    b.Property<int>("PublicationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PublicationDescription");

                    b.Property<string>("PublicationImage");

                    b.Property<string>("PublicationName")
                        .HasColumnName("PublicationName")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("PublicationId");

                    b.HasIndex("PublicationName")
                        .IsUnique()
                        .HasFilter("[PublicationName] IS NOT NULL");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Book", b =>
                {
                    b.HasOne("apiOnlineBookStoreAdmin.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("apiOnlineBookStoreAdmin.Models.BookCategory", "BookCategory")
                        .WithMany("Books")
                        .HasForeignKey("BookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("apiOnlineBookStoreAdmin.Models.Publication", "Publication")
                        .WithMany("Books")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.Order", b =>
                {
                    b.HasOne("apiOnlineBookStoreAdmin.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("apiOnlineBookStoreAdmin.Models.OrderBook", b =>
                {
                    b.HasOne("apiOnlineBookStoreAdmin.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("apiOnlineBookStoreAdmin.Models.Order", "Order")
                        .WithMany("OrderBook")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
